### PR TITLE
Add new page for people who've been conditionally accepted?

### PR DESCRIPTION
**Pull request by Haseeb-Qureshi**

### CODE REVIEW

**Comment by Haseeb-Qureshi** [comment]
Haven't tested this because don't know how! Just pattern matching. How do you test this thing?

**Comment by Chebotarev** [comment]
You can test this by running `bundle exec jekyll serve`, and then it will be hosted on localhost:4000. Note if you go to the root page, it just redirects to appacademy.io. Your new page will show up at http://localhost:4000/pre-course/conditional-acceptance/

**Comment by Chebotarev** [comment]
I just tested it out and it looks good, I'm going to go ahead and merge this in.

**Comment by Haseeb-Qureshi** [comment]
Sounds good, thanks!

Haseeb Qureshi
haseebq.com

**Pull request merged**
